# The schema of latest Azure Pipeline syntax at: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema
name: Build backend by Azure Pipeline
jobs:
  - job: installing
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
          checkLatest: true
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |          
            npm install
            npm test
            npm build
