on:
  push:
    branches: [master]
  pull_request:
    branches: [master, develop]
jobs:
  build:   
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/ZQ-jhon/API
        azure-pipeline-name: 'Backend CI Bot'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }
  
